# Disable these two since Jekyll now uses `kramdown` and`rouge` by default.
#
# markdown: redcarpet
# highlighter: pygments

# plugins used in the site
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll- sitemap

# Permalinks
permalink:        pretty

# Setup
title:            Zijie
tagline:          'Life stories'
description:      'A blogpost about my life and adventures. Data Engineering with Spark, Piano and Organ, Brazilian Jiu-Jitsu and Math'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'William Zijie Zhang'
  url:            https://transurgeon.github.io/

gems: [jekyll-paginate]
paginate: 5
# paginate_path: "/baseurl/page:num/"

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/Transurgeon/Transurgeon.github.io
