# Disable these two since Jekyll now uses `kramdown` and`rouge` by default.
#
# markdown: redcarpet
# highlighter: pygments

# plugins used in the site
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll- sitemap

# Permalinks
permalink:        pretty

# Setup
title:            Zijie
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'William Zijie Zhang'
  url:            https://github.com/Transurgeon

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Transurgeon
